import { chromium } from "/Users/ad/careerapp2/node_modules/playwright-core/index.mjs"
const browser = await chromium.launch()
const errs=[]
const ctx = await browser.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2 })
const page = await ctx.newPage()
page.on("pageerror", (e) => errs.push(e.message))
await page.goto("http://localhost:5175/")
await page.locator("text=Jobs right now").scrollIntoViewIfNeeded()
await page.waitForTimeout(1500)
await page.screenshot({ path: "shots/f-1.png" })
await page.getByRole("button", { name: "Add filter" }).first().click()
await page.waitForTimeout(300)
await page.screenshot({ path: "shots/f-2.png" })
await page.getByRole("button", { name: "Workplace" }).click()
await page.waitForTimeout(400)
await page.screenshot({ path: "shots/f-3.png" })
const w = await page.evaluate(() => document.documentElement.scrollWidth)
console.log(errs, w)
await browser.close()
