import { chromium } from "/Users/ad/careerapp2/node_modules/playwright-core/index.mjs"
const browser = await chromium.launch()
const profile = { permit: "orientation_year", birth: 1999, abroad: 20, origin: "non_eu", dutch: "none", salary: "", tailor: false, cv: "", positions: [], education: [], skills: [], languages: [], occ: "", onboarded: true, columns: [], columnTypes: {}, notes: {}, people: [], views: {}, templates: null, name: "", headline: "", place: "", about: "", avatar: "" }
const ctx = await browser.newContext({ viewport: { width: 1000, height: 1500 }, deviceScaleFactor: 1.5 })
await ctx.addInitScript((p) => { localStorage.setItem("careersim.profile", JSON.stringify(p)); localStorage.setItem("careersim.saved", JSON.stringify(["p1279", "p1101", "p1230"])) }, profile)
const page = await ctx.newPage()
await page.goto("http://localhost:5175/")
await page.waitForSelector("text=job search", { timeout: 30000 })
await page.getByRole("button", { name: /^Sort/ }).click()
await page.waitForTimeout(400)
await page.screenshot({ path: "shots/s-open.png" })
await page.getByRole("button", { name: "Company", exact: true }).click()
await page.getByRole("button", { name: "Company" }).first().waitFor()
await page.screenshot({ path: "shots/s-after.png" })
await browser.close()
